### ISSUE TITLE
Add selectableFields to NodeMaintenance

### ISSUE THREAD

**Issue by adrianchiris** [Mellanox/maintenance-operator#17]
## What would you like to be added?

in k8s 1.31 selectableFields for CRD was promoted to stable[1]
once controller tools support selectable fields [2] we should use the defined markers to add the following selectable fields to NodeMaintenance CRD:

```
spec:
  selectableFields:
  - jsonPath: .spec.requestorID
  - jsonPath: .spec.nodeName
```

this will allow to list NodeMaintenance by requestorID and nodeName.

[1] https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#crd-selectable-fields
[2] https://github.com/kubernetes-sigs/controller-tools/issues/1039
